[build]
  command = "npm run build && cp public/* out/"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/zh-CN/*"
  to = "/zh-CN"
  status = 200

[[redirects]]
  from = "/en-US/*"
  to = "/en-US"
  status = 200

[[redirects]]
  from = "/*"
  to = "/zh-CN"
  status = 200 