[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/zh"
  to = "/zh-CN"
  status = 301
  force = true

[[redirects]]
  from = "/en"
  to = "/en-US"
  status = 301
  force = true 